resources:
- repo: self
queue:
  name: Hosted VS2017

steps:
- script: |
   pip install -r requirements.txt
   mkdocs build  
  displayName: Install the MkDocs + do a build

- task: AzureFileCopy@2
  displayName: AzureBlob File Copy
  inputs:
    SourcePath: site
    azureSubscription: '<Subscription-Name> (<Subscription-ID>)'
    Destination: AzureBlob
    storage: mkdocsvstsautomation
    ContainerName: '$web'